name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.1"

      - uses: leafo/gh-actions-luarocks@v6

      - name: Install tooling
        run: luarocks install luacheck && luarocks install busted

      - name: Luacheck
        run: luacheck .

      - name: Busted
        run: busted
